# Prometheus Alert Rules

groups:
- name: operations
  rules:

  - alert: NodeCPUUsage
    expr: (100 - (avg by (instance) (irate(node_cpu{name="node-exporter",mode="idle"}[5m])) * 100)) > 85
    for: 10m
    labels:
      severity: slack
    annotations:
      summary: "{{$labels.instance}}: High CPU usage detected"
      description: "{{$labels.instance}}: CPU usage is above 75% (current value is: {{ $value }})"
      
